name: Alex Rajewski
bio: 'A Botanist with a Mild Addiction to Science Fiction'
picture: 'assets/images/mybio.jpg'

# url: http://rajewski.github.io
url: http://localhost:3000

# if it's an external image, update below for true
external-image: false

permalink: /:title/

markdown: kramdown
highlighter: rouge

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't have any of social below, comment the line
twitter: rajewski
linkedin: alex-rajewski-74b492103
github: rajewski
email: Alex.C.Rajewski+website@gmail.com

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need projects, comment the *projects* configs below
projects: true
publications: true
about: true
CV: true

# do you want to show the "read time" of the posts?
read-time: false

# do you want some animations?
animation: true

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh]
